### ISSUE TITLE
wavmap/specidentify ZeroDivisionError

### ISSUE THREAD

**Issue by knordsieck** [saltastro/polsalt#35]
Starting specpolwavmap

Pysalt Version: v0.5dev

ARC: image 40 GRATING PG0900 GRANG    9.000 ARTIC   24.250 LAMP HgAr
  Split Row: 1018 
SPECIDENTIFY images=arc_40_0.fits 
linelist=/usr/users/brian/sal/brian/iraf/RSS/salt/pysalt/data/linelists/HgAr.salt 
outfile=arcdb_40_0.txt guesstype=rss guessfile=arcdb_40_0.txt 
automethod=Matchlines function=legendre order=3 rstep=20 rstart=538 mdiff=20 
thresh=3 niter=5 smooth=3 subback=0 inter=True startext=0 clobber=True 
textcolor=black logfile=specpol20151219.log verbose=True

2016-06-11 16:28:02 MESSAGE ------------------------------------------
Starting specidentify

2016-06-11 16:28:02 MESSAGE ------------------------------------------
Proccessing extension 1 in  arc_40_0.fits
2016-06-11 16:28:02 ERROR --------------------------------------------
float division by zero
Traceback (most recent call last):
  File "/usr/users/brian/sal/brian/iraf/RSS/salt/pysalt/lib/saltsafelog.py", line 196, in logging
    yield log
  File "/usr/users/brian/sal/brian/iraf/RSS/salt/pysalt/saltspec/specidentify.py", line 165, in specidentify
    wcen / 1e7, rss.alpha(), -rss.beta())
  File "/usr/local/lib/python2.7/site-packages/PySpectrograph/Spectrograph/Spectrograph.py", line 133, in calc_resolution
    return w/self.calc_resolelement(alpha, beta)
ZeroDivisionError: float division by zero
[arc_40_0.zip](https://github.com/saltastro/polsalt/files/310990/arc_40_0.zip)

**Comment by crawfordsm** [comment]
In the image header, there needs to be two keywords changed as they do not work with specidentify.  The following two should be changed:

```
 MASKID  = 'P000000P06        ' / Slitmask Bar Code
 MASKTYP = 'MOS               ' / Slitmask mask type
```

Should be changed to 

```
MASKID = 'P001000P06'
MASKTYP='LONGSLIT'
```

The code reads the slitwidth from the mask name and so is reading a slit width of zero which was then causing the divide by zero error.   I should probably add a catch in specid for that, but those changes to the header should make the arc run

**Comment by knordsieck** [comment]
Steve-

Aha!  I caught MASKTYP: I uncommented your force of MASKTYP to LONGSLIT (line 78 in specpolwavmap).  It looks like I should also force the MASKID to have a sensible longslit slitwidth, if necessary.  (all until we have MOS working, of course).

Then I’ll close out Issue #8.

Ken

**Comment by knordsieck** [comment]
Close #35
